<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.53" os="" host="SC_8918-S1" qcserver="http://s1-alm-prod:8080/qcbin" qcproject="PFS.ProdRuns_Branch_Plus"><DocLocation><![CDATA[C:\Users\ap1\Documents\GitHub\qTestDemo\Add_CPI_Approved]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Add_CPI_Approved]]></DName>
<Res><![CDATA[Add_CPI_Approved]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj ><![CDATA[Query]]></Obj>
<Details ><![CDATA[select BRANCH_SETUP_STATE from BRANCH_SETUP_TBL;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:05]]></Time>
<TimeTick>1577356325</TimeTick>
<NodeArgs eType="User" icon="5" nRep="8" >
<Disp><![CDATA[Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj ><![CDATA[Test Data Get Query]]></Obj>
<Details ><![CDATA[select BRANCH_SETUP_STATE from BRANCH_SETUP_TBL;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:05]]></Time>
<TimeTick>1577356325</TimeTick>
<NodeArgs eType="User" icon="5" nRep="9" status="Passed" >
<Disp><![CDATA[Test Data Get Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj ><![CDATA[Query]]></Obj>
<Details ><![CDATA[select VERSION from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:06]]></Time>
<TimeTick>1577356326</TimeTick>
<NodeArgs eType="User" icon="5" nRep="10" >
<Disp><![CDATA[Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[Test Data Get Query]]></Obj>
<Details ><![CDATA[select VERSION from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:06]]></Time>
<TimeTick>1577356326</TimeTick>
<NodeArgs eType="User" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Test Data Get Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA[Query]]></Obj>
<Details ><![CDATA[select build_nbr from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:06]]></Time>
<TimeTick>1577356326</TimeTick>
<NodeArgs eType="User" icon="5" nRep="12" >
<Disp><![CDATA[Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[Test Data Get Query]]></Obj>
<Details ><![CDATA[select build_nbr from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:06]]></Time>
<TimeTick>1577356326</TimeTick>
<NodeArgs eType="User" icon="5" nRep="13" status="Passed" >
<Disp><![CDATA[Test Data Get Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj ><![CDATA[Custom Results Folder Path]]></Obj>
<Details ><![CDATA[\\sfcnas-cl-201\Shared\AUTOMATION\BranchPlus\OH\TestResults\LastRun_10_12_2019_5_52_28]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:07]]></Time>
<TimeTick>1577356327</TimeTick>
<NodeArgs eType="User" icon="5" nRep="14" status="Passed" >
<Disp><![CDATA[Custom Results Folder Path]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[Query]]></Obj>
<Details ><![CDATA[select * from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:07]]></Time>
<TimeTick>1577356327</TimeTick>
<NodeArgs eType="User" icon="5" nRep="15" >
<Disp><![CDATA[Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Test Data Get Query]]></Obj>
<Details ><![CDATA[select * from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:07]]></Time>
<TimeTick>1577356327</TimeTick>
<NodeArgs eType="User" icon="5" nRep="16" status="Passed" >
<Disp><![CDATA[Test Data Get Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Query]]></Obj>
<Details ><![CDATA[select * from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:07]]></Time>
<TimeTick>1577356327</TimeTick>
<NodeArgs eType="User" icon="5" nRep="17" >
<Disp><![CDATA[Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA[Test Data Get Query]]></Obj>
<Details ><![CDATA[select * from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:07]]></Time>
<TimeTick>1577356327</TimeTick>
<NodeArgs eType="User" icon="5" nRep="18" status="Passed" >
<Disp><![CDATA[Test Data Get Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ Dialog ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:12]]></Time>
<TimeTick>1577356332</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="20" >
<Disp><![CDATA[[ Dialog ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ Dialog ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:17]]></Time>
<TimeTick>1577356337</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="22" >
<Disp><![CDATA[[ Dialog ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[BranchPlus]]></Obj>
<Details plainTxt="False" ><![CDATA[PbWindow]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:20]]></Time>
<TimeTick>1577356340</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[BranchPlus.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:20]]></Time>
<TimeTick>1577356340</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="25" >
<Disp><![CDATA[BranchPlus.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:20]]></Time>
<TimeTick>1577356340</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Run "C:\BranchRoot\App\sfc_branch_plus\RunBranchPlus.CMD",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\BranchRoot\App\sfc_branch_plus\RunBranchPlus.CMD",1]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:20]]></Time>
<TimeTick>1577356340</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="29" status="Passed" >
<Disp><![CDATA[Run "C:\BranchRoot\App\sfc_branch_plus\RunBranchPlus.CMD",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="28" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ Dialog ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:26]]></Time>
<TimeTick>1577356346</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="31" >
<Disp><![CDATA[[ Dialog ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ Dialog ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:31]]></Time>
<TimeTick>1577356351</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="33" >
<Disp><![CDATA[[ Dialog ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ sle_userid ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 20000]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:31]]></Time>
<TimeTick>1577356351</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="35" >
<Disp><![CDATA[[ sle_userid ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ sle_userid ].SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["support"]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:31]]></Time>
<TimeTick>1577356351</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="37" >
<Disp><![CDATA[[ sle_userid ].SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ sle_password ].SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["tpbtso"]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:31]]></Time>
<TimeTick>1577356351</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="39" >
<Disp><![CDATA[[ sle_password ].SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ OK ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:31]]></Time>
<TimeTick>1577356351</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="41" >
<Disp><![CDATA[[ OK ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ sle_userid ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 20000]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:31]]></Time>
<TimeTick>1577356351</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="43" >
<Disp><![CDATA[[ sle_userid ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ sle_userid ].SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["ap1"]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:31]]></Time>
<TimeTick>1577356351</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="45" >
<Disp><![CDATA[[ sle_userid ].SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ sle_password ].SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["Newuser27"]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:32]]></Time>
<TimeTick>1577356352</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="47" >
<Disp><![CDATA[[ sle_password ].SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ Ok ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:32]]></Time>
<TimeTick>1577356352</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="49" >
<Disp><![CDATA[[ Ok ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ Dialog ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:42]]></Time>
<TimeTick>1577356362</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="51" >
<Disp><![CDATA[[ Dialog ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[BranchPlus.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 20000]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:42]]></Time>
<TimeTick>1577356362</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="53" >
<Disp><![CDATA[BranchPlus.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="24" status="Passed" >
<Disp><![CDATA[BranchPlus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[Query to Identify the Cash Drawer & Set Pwd]]></Obj>
<Details ><![CDATA[Update bp_employee_tbl set security_level='900', password ='auto123' where userid <>'support' and empl_type in ('16A', 'MGR') ;

Update security_groupings set group_name='900' where user_name <>'support' and user_name in (select userid from bp_employee_tbl where empl_type in ('16A', 'MGR'));

SELECT et.empl_id, et.userid
        FROM bp_employee_banking_affil_tbl cdt inner join bp_employee_tbl et
        on cdt.empl_id=et.empl_id
        where et.empl_status='ACTIVE' and et.empl_type in ('16A', 'MGR') and et.security_level >= 900
        group by et.empl_id, et.userid
        having count(et.userid) > 2;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:42]]></Time>
<TimeTick>1577356362</TimeTick>
<NodeArgs eType="User" icon="5" nRep="54" >
<Disp><![CDATA[Query to Identify the Cash Drawer & Set Pwd]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA[Query]]></Obj>
<Details ><![CDATA[Update bp_employee_tbl set security_level='900', password ='auto123' where userid <>'support' and empl_type in ('16A', 'MGR') ;

Update security_groupings set group_name='900' where user_name <>'support' and user_name in (select userid from bp_employee_tbl where empl_type in ('16A', 'MGR'));

SELECT et.empl_id, et.userid
        FROM bp_employee_banking_affil_tbl cdt inner join bp_employee_tbl et
        on cdt.empl_id=et.empl_id
        where et.empl_status='ACTIVE' and et.empl_type in ('16A', 'MGR') and et.security_level >= 900
        group by et.empl_id, et.userid
        having count(et.userid) > 2;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:42]]></Time>
<TimeTick>1577356362</TimeTick>
<NodeArgs eType="User" icon="5" nRep="55" >
<Disp><![CDATA[Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[Test Data Get Query]]></Obj>
<Details ><![CDATA[Update bp_employee_tbl set security_level='900', password ='auto123' where userid <>'support' and empl_type in ('16A', 'MGR') ;

Update security_groupings set group_name='900' where user_name <>'support' and user_name in (select userid from bp_employee_tbl where empl_type in ('16A', 'MGR'));

SELECT et.empl_id, et.userid
        FROM bp_employee_banking_affil_tbl cdt inner join bp_employee_tbl et
        on cdt.empl_id=et.empl_id
        where et.empl_status='ACTIVE' and et.empl_type in ('16A', 'MGR') and et.security_level >= 900
        group by et.empl_id, et.userid
        having count(et.userid) > 2;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:42]]></Time>
<TimeTick>1577356362</TimeTick>
<NodeArgs eType="User" icon="5" nRep="56" status="Passed" >
<Disp><![CDATA[Test Data Get Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[BranchPlus]]></Obj>
<Details plainTxt="False" ><![CDATA[PbWindow]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:42]]></Time>
<TimeTick>1577356362</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[BranchPlus.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:42]]></Time>
<TimeTick>1577356362</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="59" >
<Disp><![CDATA[BranchPlus.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ w_bp_logon ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 20000]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:44]]></Time>
<TimeTick>1577356364</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="61" >
<Disp><![CDATA[[ w_bp_logon ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ sle_userid ].SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["DT"]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:44]]></Time>
<TimeTick>1577356364</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="63" >
<Disp><![CDATA[[ sle_userid ].SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ sle_password ].SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["auto123"]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:44]]></Time>
<TimeTick>1577356364</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="65" >
<Disp><![CDATA[[ sle_password ].SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[[ OK ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:44]]></Time>
<TimeTick>1577356364</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="67" >
<Disp><![CDATA[[ OK ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ Yes ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 2000]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:44]]></Time>
<TimeTick>1577356364</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="69" >
<Disp><![CDATA[[ Yes ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ No ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:44]]></Time>
<TimeTick>1577356364</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="71" >
<Disp><![CDATA[[ No ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="58" >
<Disp><![CDATA[BranchPlus]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj ><![CDATA[Login With user assigned with Cash Drawer >> DT >> StateName >> OH]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:45]]></Time>
<TimeTick>1577356365</TimeTick>
<NodeArgs eType="User" icon="5" nRep="72" status="Passed" >
<Disp><![CDATA[Login With user assigned with Cash Drawer >> DT >> StateName >> OH]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA[Query]]></Obj>
<Details ><![CDATA[Select * from support.bp_account_tbl where acct_status ='APPROVED' and acct_type=55]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:50]]></Time>
<TimeTick>1577356370</TimeTick>
<NodeArgs eType="User" icon="5" nRep="73" >
<Disp><![CDATA[Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[Test Data Get Query]]></Obj>
<Details ><![CDATA[Select * from support.bp_account_tbl where acct_status ='APPROVED' and acct_type=55]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:50]]></Time>
<TimeTick>1577356370</TimeTick>
<NodeArgs eType="User" icon="5" nRep="74" status="Passed" >
<Disp><![CDATA[Test Data Get Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA[Failed to runSQLQuery]]></Obj>
<Details ><![CDATA[Either BOF or EOF is True, or the current record has been deleted. Requested operation requires a current record.]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:50]]></Time>
<TimeTick>1577356370</TimeTick>
<NodeArgs eType="User" icon="5" nRep="75" status="Failed" >
<Disp><![CDATA[Failed to runSQLQuery]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[Query]]></Obj>
<Details ><![CDATA[select VERSION from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:50]]></Time>
<TimeTick>1577356370</TimeTick>
<NodeArgs eType="User" icon="5" nRep="76" >
<Disp><![CDATA[Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj ><![CDATA[Test Data Get Query]]></Obj>
<Details ><![CDATA[select VERSION from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:50]]></Time>
<TimeTick>1577356370</TimeTick>
<NodeArgs eType="User" icon="5" nRep="77" status="Passed" >
<Disp><![CDATA[Test Data Get Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[Query]]></Obj>
<Details ><![CDATA[select build_nbr from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:50]]></Time>
<TimeTick>1577356370</TimeTick>
<NodeArgs eType="User" icon="5" nRep="78" >
<Disp><![CDATA[Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj ><![CDATA[Test Data Get Query]]></Obj>
<Details ><![CDATA[select build_nbr from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:50]]></Time>
<TimeTick>1577356370</TimeTick>
<NodeArgs eType="User" icon="5" nRep="79" status="Passed" >
<Disp><![CDATA[Test Data Get Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA[Query]]></Obj>
<Details ><![CDATA[select * from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:50]]></Time>
<TimeTick>1577356370</TimeTick>
<NodeArgs eType="User" icon="5" nRep="80" >
<Disp><![CDATA[Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj ><![CDATA[Test Data Get Query]]></Obj>
<Details ><![CDATA[select * from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:50]]></Time>
<TimeTick>1577356370</TimeTick>
<NodeArgs eType="User" icon="5" nRep="81" status="Passed" >
<Disp><![CDATA[Test Data Get Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj ><![CDATA[Failed in step/Function get_Account_Id_From_DB]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:51]]></Time>
<TimeTick>1577356371</TimeTick>
<NodeArgs eType="User" icon="5" nRep="82" status="Failed" >
<Disp><![CDATA[Failed in step/Function get_Account_Id_From_DB]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj ><![CDATA[Query]]></Obj>
<Details ><![CDATA[select VERSION from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:51]]></Time>
<TimeTick>1577356371</TimeTick>
<NodeArgs eType="User" icon="5" nRep="83" >
<Disp><![CDATA[Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj ><![CDATA[Test Data Get Query]]></Obj>
<Details ><![CDATA[select VERSION from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:51]]></Time>
<TimeTick>1577356371</TimeTick>
<NodeArgs eType="User" icon="5" nRep="84" status="Passed" >
<Disp><![CDATA[Test Data Get Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj ><![CDATA[Query]]></Obj>
<Details ><![CDATA[select build_nbr from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:51]]></Time>
<TimeTick>1577356371</TimeTick>
<NodeArgs eType="User" icon="5" nRep="85" >
<Disp><![CDATA[Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA[Test Data Get Query]]></Obj>
<Details ><![CDATA[select build_nbr from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:51]]></Time>
<TimeTick>1577356371</TimeTick>
<NodeArgs eType="User" icon="5" nRep="86" status="Passed" >
<Disp><![CDATA[Test Data Get Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj ><![CDATA[Query]]></Obj>
<Details ><![CDATA[select * from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:51]]></Time>
<TimeTick>1577356371</TimeTick>
<NodeArgs eType="User" icon="5" nRep="87" >
<Disp><![CDATA[Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj ><![CDATA[Test Data Get Query]]></Obj>
<Details ><![CDATA[select * from bp_branch_setup_tbl;]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:51]]></Time>
<TimeTick>1577356371</TimeTick>
<NodeArgs eType="User" icon="5" nRep="88" status="Passed" >
<Disp><![CDATA[Test Data Get Query]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[12/26/2019 - 5:32:51]]></Time>
<TimeTick>1577356371</TimeTick>
<NodeArgs eType="General" icon="12" nRep="89" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/26/2019 - 5:32:05" eTime="12/26/2019 - 5:32:51" passed="16" failed="2" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Add_CPI_Approved Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="12/26/2019 - 5:32:04" eTime="12/26/2019 - 5:32:51" passed="16" failed="2" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Add_CPI_Approved Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>